# Generated by Django 6.0.1 on 2026-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='request_payload',
            new_name='request_body',
        ),
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='response_payload',
            new_name='response_body',
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
