# Generated by Django 6.0.1 on 2026-01-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_timestamp_apirequestlog_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequestlog',
            old_name='http_method',
            new_name='method',
        ),
    ]
