# Generated by Django 6.0.1 on 2026-01-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_http_method_apirequestlog_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10),
        ),
    ]
